#include <cairo/cairo.h>
#include <string>
#include "opencv2/highgui/highgui.hpp"
#include <iostream>
#include <opencv2/imgproc.hpp>
#include <random>

#include <vector>

#include <iostream>
#include <fstream>
#include <string>
#include <fstream>


using namespace cv;
using namespace std;
using std::vector;

string BASE = "/Volumes/Data/WORKSPACE/git/bagiks/CMT-Text-Detection/";
//string  texts[] = {"JIA","ZHOU","DOAN","NGOC","HAI","NGUYEN","THITHUHA","TADASHI","YOSHIDA","SHAW","SHANDRO","WENCHUNG","HSU","THI","LIEN","TRAN","VIET","HA","PHUNG","DUONG","SON","ALEKSEY","VARNAVIN","KWEONJIN","UER","TINH","MINH","TRANG","HUYNH","NAOKO","KAGEYAMA","DANG","TIEN","VADIM","ZHAROV","VAN","KIEN","PHAN","THU","THUY","TUYET","MAI","LE","HONG","ANDREAS","REINECKE","LUU","BA","TRI","WENDY","HOOD","HEDWIG","RACQUET","HOANG","ANH","PHUONG","JAMES","MCNEILL","YOUNG","DAL","WILLIAM","DOUGLAS","MASON","DAVID","MEYER","TOSHIO","CHIBA","TRINH","THANH","TUAN","VIKTORIIA","GRUDNYNA","PENG","KOK","TAN","PETER","GLEESON","DUC","CUONG","LANH","MR","KIYOSHI","MATSUI","MANH","HUNG","RONNY","CHUNG","CHOI","HWA","JUNG","HUONG","HOSOKAWA","SHO","LO","QUOC","PHONG","WU","TUNG","PI","TANG","LONG","THANG","KHA","YOSHIHARU","OKUDA","SHIGERU","SATO","KAGAMI","SABURO","DANIEL","KHOA","PHAM","PHI","TRUONG","BUI","XUAN","YAP","HOCK","GUAN","DUK","HEE","SOHN","IKETANI","KATHRYN","B","ZIGENBINE","TRUNG","PHUOC","TAKAKO","MURAYAMA","CLAUDINE","PRUDENCE","KAZUHIRO","DO","THAO","TRAM","MASAO","TAKATA","VERAN","STEPHAN","KIM","SUNG","HYUN","SINH","VINH","ANDRE","GAUVRIT","YOSHITAKA","NAKATANI","MICHAEL","GERARD","SULLIVAN","HELMUT","WOLFGANG","EHNES","PATRICE","DINH","LAM","YI","SANGYEOB","ALA","P","T","QUYNH","LUAN","NGO","KIEU","LAN","TOGAMI","YOSHIRO","GREGORY","JOHN","COSTELLOE","YASUO","ITO","KI","UNG","LUA","TAKASHI","FUKAGAWA","HUBERTUS","WIERTS","CONG","DUNG","VI","TRONG","KAZUYUKI","OYA","DAN","LIN","CHANG","SHENG","BERND","SIEGEMUND","KAMBIZ","GHAWAMI","MAKOTO","KIMURA","MITSUGU","KAJIOKA","BESLY","MATTHIAS","KAUFMANN","AKIMITSU","FUJII","JUHEE","JIN","WON","KYU","LEE","HAYASHI","HIDETOSHI","LEVAXI","VO","QUANG","LIEM","YASUDA","MASAHIRO","NAKANISHI","HIROYUKI","YOSHIHISA","TAKASHINA","OTSUYAMA","LY","NHUT","DAO","JOERG","TU","TAM","KIBERT","ANG","TIAN","KEE","LA","KAWASAKI","MASARU","BICH","LUC","HASEBE","RAVINDER","KALRA","THE","DIEU","FUJIYAMA","DOI","NGA","VICTOR","HIROKO","TOMITA","AMACH","HUY","KIYOFUMI","BANAKA","TUYEN","NAM","TOSHIKAZU","SUZUKI","PHU","KAZUHISA","YAMADA","BORK","THACH","TRA","BIVI","HATOUL","HIROFUMI","KUNITANI","THUAN","HAO","SATOSHI","HIRANO","HOWARD","RICKMAN","CHUVAND","HERVE","LAURENT","BOUARD","CHIKA","MATSUMURA","NGUYET","KHAMSONE","SEN","DOMINIQUE","JEANNE","CHIH","YUAN","TSAI","KAZUE","OKAMURA","SEIJI","NISHIZUMI","MARCEL","TJOA","TEK","MONG","MELVIN","SAKURABA","MASATO","ROGER","RAYMOND","FOURNIER","IKUKO","OLGA","RIVILIS","RIE","YAMAMOTO","SHUICHI","NAGATA","WEI","HUANG","JOSE","A","GARCIA","OHNODA","MOTTE","QUY","PIERRE","PHILLIPPE","VIALA","HIDETO","YAMAZAKI","KENJI","TAKEDA","NAOYA","KIYONO","JEON","JONG","MIN","LAI","LUYEN","QUE","HAJIME","MONZEN","INAHASHI","EMI","MAN","TAI","CHAN","BRUCE","WALTER","MIDDLETON","KHANITTHA","TSUYOSHI","KOJIMA","FACQUET","ERIC","TONG","ALAIN","FAUVY","COLIN","HOPPER","MOTOHIRO","SUMIYOSHI","J","WICKHAM","DAM","WASAMA","MICHINORI","NGAN","THENG","MENG","MIYOSHI","MASASHI","XANH","KENKICHI","TANAKA","BIEU","THOMAS","STAEHELIN","FUJINO","AKIHIKO","GIANG","AKIYOSHI","NAITO","BAC","ROY","VINCENT","FRANCIS","TOSHIKIYO","DELPHINE","UYEN","KYOKO","NAKANO","CORVO","TRUC","FULLERTON","DOWNIE","C","TO","PHUC","KITAMURA","BINH","JOONGHAE","JI","CHI","NHANH","MS","CU","YOSHIHIRO","JIMBO","HIROSHI","NAGUMO","SEISHIRO","UYAMA","THIEU","TIEU","YEN","DAU","KOZO","KINEBUCHI","HIDEFUMI","CRONJE","JOHANNES","HENDRIK","HIROMI","UMEHARA","NHUHUNG","MASAFUMI","KEIKO","ONDA","WILSON","YUKI","MORIYA","KHANH","CASHMAN","HITOSHI","YAMASHITA","HUYEN","FUKUZUMI","KOBAYASHI","TOSHIAKI","KERRY","ANN","KIMIYO","MATSUMOTO","GOUJON","KHIEM","HIRAOKA","YOSHIKI","EP","BE","HIEU","AN","LYLIA","L","LINH","PAUL","NOH","NHI","HOA","IWATA","TSUTOMU","TUONG","LIET","DOUGIAS","WELLS","SUU","HUU","NGHI","MAC","QUAN","BUU","NHON","CANH","TOAN","QUA","LOC","HO","HIROKAZU","KITAGAWA","THIEN","MILENA","NAGANO","TOMOHIRO","DUY","VY","BOND","TIMOTHY","KYUN","GIBYUNG","BELEZOVA","NATALIA","KOJI","WADA","H","WOOLHOUSE","MY","YOON","EUN","FUDEMOTO","MASAKATSU","DZUNG","THUONG","JUNGJAE","HOAI","SHAH","VIBHA","LIM","SOOK","MAY","GIA","CHINH","BAY","REGAN","ANDREW","FENG","ZHONGHAI","VUONG","SIEW","ENG","CHAU","CAVANAGH","KHOI","LU","GUANGHUA","HIEN","DONG","BIEN","CO","SEO","KISEOG","ZAIRAN","MOHDNOH","DOLENKO","SVETLANA","SASCHA","BECKER","WING","KIT","STEPHEN","PLATTS","ANTOIINE","ICHIKAWA","KAZUO","WONG","KA","KIK","VU","HOE","CAO","CAM","DAI","TET","MUN","ELIZAVETA","ELAINE","SHAN","KOH","MOC","MUOI","JUNGKYUNG","NGHIA","LICH","MACH","AI","HANG","LIANG","LOI","THONG","CHUONG","NHU","HYAO","KNUL","DIEM","YUNA","DU","VIEN","DIEP","M","HARALD","KIRSCH","DI","KAWICHAI","MISS","SOMPORN","PARK","MUHAMMAD","HANIS","ABDUL","MALI","THAI","SHIOTANI","LOH","HAK","CHONG","THUA","HANH","LAW","MOI","DAT","KHUONG","BANH","EVON","PUICHING","YEO","SHICHI","SEUNG","RUSYDI","JAMIL","DOC","KAH","WEN","CHIEN","oanh","RON","JIKUMARU","MASATOSHI","FOLEY","BAUR","MELINA","CAJAYON","JOANNE","ANGELES","VUTHI","SAO","OSHIMA","NOBUHIRO","DERVIS","AMOR","MOREIRA","PHAP","KUSAKABE","AIKAWA","MIZUTANI","CHIAKI","KInari","QUYEN","MAU","ANTOINE","KYLE","AARON","COCHRAN","DANGKHOA","tanderson","DAC","NGHIEM","RI","SOO","KONDO","KIYOMI","ROBBY","SALAMUN","KAZUKI","OMORI","LUONG","PAO","LUNG","TUFFERT","ERNST","CHUO","PING","TOMOKAZU","TSUNO","INJI","SHIN","DONGKWON","YUN","SANG","KHAI","SUONG","MAUREEN","REID","ALAN","LANSELL","SOWARD","HUE","CHO","JAE","WEON","ESCANUELA","JENNIFER","UY","KHUYEN","KISHIDA","TOMOO","UGRIT","TANYANON","PEN","KINH","KO","KAWANO","JINAH","NHUNG","TON","NU","TETSUJI","BACH","MURRAY","GIBBINS","JAEHEE","SY","TRIET","FAIZAH","FAUZI","SEMEYKO","ANNA","HYOJUNG","YU","TAESUCK","JINYONG","NG","LING","NHAN","KHANG","SUPATTRA","SUDO","BAO","NGUYLE","CAPUCHINO","THUAT","ZUBAIDI","FAHRIZAL","FAISAL","DENNIS","MD","OBAIDUR","RAHMAN","BOO","FANG","YUKA","SONE","SUNHEE","SAM","HOAN","CHEON","SANGIK","TSCHAN","BERNHARD","MAYA","HOENIG","PUI","BAE","SEONGBONG","YAGI","MASAYUKI","JASON","UMINO","YUEN","CHET","NHAT","SANTACRUZ","AURA","ELIDE","MOUTOUH","THUTRANG","TIEP","SHOJI","CHIEKO","LOAN","KIRBY","OCASTRO","VUNG","IKONNIKOV","ANDREI","HYUNMI","NIKISHINA","JANG","SUJIN","FUJITA","JEAN","RENE","DELYS","HYO","TAT","HANS","KUMPEL","WHANG","JA","MN","WOO","CHANH","SEONGHO","YANG","CHIA","HEEKYUNG","KHAC","KHUNG","JUYONG","THUC","TRIEN","SANADA","KENSAKU","YUVAREE","PANG","YONG","DE","HIEP","KARATSU","ITSUHIRO","KIMTHU","THINH","YOUM","DONGKOO","DUE","NHUNGH","SHIRLEY","IMASAKI","MACHIKO","MOON","SOOKYOUN","GEUNHUI","MUSHTIN","OLEG","SITI","NURHANIS","MOHAMAD","HYUNGHO","LISA","ANDREA","STEURER","LIHUA","NIZKY","JAN","KUSUMA","FENNY","SEONG","OK","CHUN","MASAYOSHI","AOKI","MINSUNG","UCHIYAMA","QIU","LINDAI","KRAUS","MARIO","TUY","DUYEN","SEOLHEE","THY","PYOUN","MOOHOON","TAWADA","TAKAHIRO","ANTHONY","PRICE","BRITTON","UESUGI","MINAMI","IANA","NGU","JORDAAN","BLOM","WATANABE","LI","YOUNGLAN","SONG","HASHIM","DUOC","BOON","NGEE","CRAIG","BRAUER","ATSUKO","OKABE","HWANG","JONATHAN","RODEN","HOI","JUNGEUN","JESSY","MG","GAYAN","SAMEERA","CHOW","CHEN","NAI","LUN","MING","VANDOAN","JIEUN","HEO","RAHN","TTUYET","GIAP","MIYAMOTO","KATSUYUKI","NAMIKI","KENTARO","LUI","SIU","JUNHO","Hau","BALI","RAMNEET","S","ELENA","Phạm","Quốc","JOANNA","ELIZABETH","NICHOLLS","ITOH","YOSHIMI","PENKOVA","SOFYA","HUIGYEONG","FOOK","OASHI","KOICHI","CHUA","SOON","KAWANAKA","HANEDA","REO","CHUANG","MIHYANG","MEIYING","KIEM","NAN","NAMIE","JINDAPORN","TRIEU","QUYET","DA","THAP","IKEMOTO","RYUJI","PALMES","KRYL","NORIYUKI","SHINBORI","TAKAFUMI","GIAU","HENG","THAN","HALIM","SUNGYOUNG","SEOL","SHINWOO","THO","YOO","SANGMI","NARASAKI","MIHO","ACHILLE","SPINACCI","SIN","KWON","SANGJOON","Fazirah","Fadzeli","PATTI","ROBERT","BOONE","BONG","KYOUN","MINORINI","EMANUELA","WYNN","MORDEY","MAUNG","LAY","MYAT","SHANE","BLACK","KENTA","PORNCHAI","PHILLIP","SOHEE","TAKAHASHI","MARTIN","ZENG","NORIO","IZUMI","COURTLAND","STRUB","CHAT","OKAY","WAH","SUEYOSHI","NGOAN","MI","HAN","LIEU","NHO","tamtran","MCDONALD","KAI","LIEW","PHAT","ZEMIN","D","HYOSHIN","AHN","DON","SALVADOR","CHANGYEON","NOVIKOVA","EKATERINA","PHUI","SAU","THAC","OH","SEOK","THIEM","CHINGHUA","MUIR","CAMPBELL","IAIN","RANG","SEE","HUA","PASCAL","HUILLET","KAZUYOSHI","FLAQUE","JAIME","OKUMURA","MANABU","KAWATANI","SHINTARO","KYOUNG","HANSSON","EVA","LOUISE","TA","THIANH","GEWAGNE","JAEEUN","BOK","HOSHI","EMIKO","NGHIEP","NAKAMURA","JUNICHI","SURBSUK","SHU","FEN","MCNICOLL","MURAO","CHENG","YOUNGWOO","EUNJU","THIHONG","THIET","NHIEN","PRANDA","MULYA","PUTRA","MITSURU","ISHIDA","KYUNG","AE","TAC","SUGIMOTO","MIEN","BYUNGSOO","YOSHITOMI","IWAGUCHI","YOSHIO","OUTRAM","SAMANTHA","ELZAKKER","JOS","NUTAN","GALLINA","Xiongcai","Liu","SEGOVIA","ANTONINO","LEON","ZHANG","TAKAGI","NAOMI","MURAOKA","YUTAKA","HIDEO","LAP","PHILIPPE","BEOMJIN","QUACH","KANG","JOOHEE","TSENG","JUI","YING","NOZOMU","JEONG","TEA","SUNGJUN","GYU","HYEON","YOUNGMEE","TSUTSUMI","TOSHIFUMI","HUUNGHIA","QUINN","LOUIS","HWEE","LENG","RADOMSKI","BRIAN","RYU","JIHYE","BYUNG","HIE","JIUNN","YIH","UOZAKI","NISHIDE","YIFUJIA","JEUNGHOON","MA","JING","SHEN","YOJI","SHIBUTANI","COULON","PILLOT","LUCIE","DOWE","MINYOUNG","KOSHIHARA","HYEKANG","CLERCQ","PATRICK","SWEE","JIANG","XIA","TZU","JILIAN","JEEYEON","ngalyly","JUN","NAMGUNG","WESTWOOD","HENRY","W","G","IN","JOON","SOH","KHEE","FONG","BANG","FUKASU","SACHIKO","SUN","KHUU","DICH","NOMURA","KUNIO","DIEN","PIYANAT","SUZUYAMA","YASUHIRO","ISHIKAWA","CHIANG","SI","FROPOS","MARK","SHUMPEI","HASEGAWA","THUYEN","BAHAR","YUSUF","EUNMI","SUK","CARROLL","KUO","BU","YOUNGJA","YAMAUCHI","TOMOE","CHIU","MINGTSUNG","RUI","MOK","HAERI","JOUBERT","WOUTER","GILDONG","VANLOI","VUC","BUMJIN","SE","NONG","FRANCINE","CLAROT","NIKITIN","MARCIA","PAZOS","MONTEIRO","LEONG","YEW","HEEJIN","YUNG","byungchul","NICOLA","VOTHUYHA","DOLMATOVA","YULIA","SHIMURA","STEFFEN","FORTHOFER","CUI","FAN","RONALD","JUYEON","BYEONG","IL","Lorenzo","SIYOON","JOO","PRADANTI","GYUWAN","REIS","CHU","MAXIME","GUILLAUME","CHEUNG","YIP","MINAM","CHOR","AMY","XIANG","DONGXIAO","GAD","SHIMON","SZNAJDER","SHINJI","KENNA","JOACHIM","JOSEF","HEINRICH","AAAA","HYEONSUK","LOW","BENG","BAK","JEAVONS","FELLOWS","MIYAZAKI","HISAKO","MANKYUNG","BYUNGJIN","KOKI","JEFFREY","DAYPUYAT","NOREEN","JEONGSOOK","THIERRY","ANGLADA","HEINZ","GEIS","FUNG","CHEE","KONG","WEE","TECK","MINORU","MASUJIMA","KUANG","TSUEI","PAREKH","YASH","KUMAR","HASMUKH","CAN","ky","FOSTER","JINKYUNG","NICO","BURWITZ","MEIER","ALFRED","WILHELM","Olivier","Lamirault","NINH","SENG","JIYOUNG","MARIA","SHERIELYN","CRUZAT","SEONGWHAN","HERRON","Joseph","KOLOSOV","HYOGIL","Sa","UT","NHA","TUOI","ILL","morita","GOH","JIAN","TING","DOBRYDINA","KEIZO","OMURA","AWANE","JEOW","YOSHIHITO","UEKI","PIRJO","LIISA","VILLMAN","YOUKIM","SUPAPORN","MALDEREN","V","MOHD","MAHMOOD","HIDEYUKI","IEZATO","DEAN","DONGHWI","HIDETSUGU","KUEI","TENG","HAYASE","YAROSLAV","IVANOV","KHUE","Dunghth","HIRATE","YOSUKE","TSZ","CHIK","JAY","thuhien","MAEDA","SANA","MAHO","MINAH","VIKTORIA","JANE","KINGSLEY","SHIBAYAMA","EIICHI","SU","ISA","RAUL","PAREDES","HOANNG","YOUNGSUK","JU","SEULKI","JOUNG","youn","kyong","Yeon","Koo","Keng","Hyung","HEERA","GARY","WARREN","WEBB","TRAC","KOIDE","BYEONGJIN","HYEHYUN","GAM","HAESSIG","DUTHY","GARTH","TE","HC","LUCAS","CHAI","LOONG","TAEHWAN","JENG","UEDA","NO","HYEJUNG","TAE","KYEONG","HUAN","ROBERTA","KUMAI","KITANO","MASAAKI","KE","PEI","HAOSONG","TSUNODA","JINHO","KODAMA","OO","GTA","Q","ASS","ASDASD","DOHYUNG","YEE","JAEJEONG","Seungchan","KATSUYO","TEIK","HOK","EDWARD","VOON","HUI","LEO","KAMARIAH","BAKAR","MINSEOK","TAMURA","MASAKAZU","VANTAI","HOIL","IWASA","AKIHISA","CHEUL","HOP","SIMON","BAKER","MOHAMED","SMITH","HONGJU","VANQUYET","POSOKHOVA","LARISA","SHIMOMURA","CHIHO","HSI","QI","HEAJUNG","LEW","WENG","YEOW","UMEDA","HIROKI","KOHIRA","BONGHWAN","JUNGRYEOL","TRACH","BUMSUK","HOTTA","KERTELICS","XIAN","DOANH","AW","EUNGJIN","ALEXANDER","MEAGHAN","HILL","CHANGHWAN","Y","PANN","MYUN","BURNES","JOY","JEONGYEON","NDAEYO","UKO","NGOCHIEP","DUAN","JIALI","POLLARD","THERESE","LUT","SUKBAE","LEI","TODA","HOKO","SEMI","BAEK","KHONG","YOONKEUN","YUJI","SHIRAI","MOTOYUKI","SO","CHING","TATEWAKI","KEIICHI","ELLA","RACHIT","MATHUR","silver","KAWAMATA","TORU","THIAM","HUAT","KAGA","AKIHIRO","LOSKUTOV","ANTON","PARSONS","TAO","RIM","SOYEON","LAU","LEUNG","BEE","HOON","TAMARA","QUIRK","THAU","NABATA","HARUMI","PON","WAI","MIYEON","QUECK","JIE","NA","EUNSUN","DMITRY","HSIN","thanhha","TOMOHIKO","SAKAGUCHI","NHUAN","HEESEO","CUC","THOI","HE","MINGMING","KEIJI","SUKHUI","WRIGHT","NOBLE","NABETA","KAZUNORI","BENJAMIN","JEE","YONGJUN","LUAT","SUNGKI","Lê","BORIM","Imanishi","HYOEN","REBECCA","ROBINSON","NODA","HON","AH","NORIKO","CHIN","TAP","IRINA","FOMICHEVA","DEVANI","DEVIKS","MIZUOCHI","YOUMI","SUNAMURA","SASAKI","TAKIMOTO","NOBORU","IBRAHIM","DAVIS","ARNOUD","MISONG","AINAMTIP","PIMFUN","sihyung","ROJO","OLIVIA","JUAN","MANUE","DzungNV","KRIS","SAI","JONGSEOK","DAHYE","NISHIO","KATSUMI","HITOMI","YOKO","TOMIOKA","OHASHI","SHOICHI","miguen","YOKE","HILEY","KWANGSOO","TEST","GH","HIRAKAWA","KAZUMA","BAT","SHIH","KYUNGHEE","SAMUEL","TAY","CHEOLGWON","KHOE","HUIJUNG","OGAWA","TAICHIRO","JACK","EDMONDSON","VUI","HUANBAOER","ONG","DANNY","KYUNGA","CHOE","SUNJUNG","MEGUMI","HODGSON","IAN","EPUOSE","ILHAM","AKBAR","ADHIGUNA","E","Satish","Sabhlok","HYUNJIN","THOA","PHYO","PAING","THAM","SOMALY","TAKEZAWA","TAKUYA","ISHII","MIKI","ANANDA","SUTRISNO","TAEHEE","JUNGMIN","TUE","JO","SEUNGWON","SHI","YINGFENG","MUSNER","LEONE","AYA","KOSLOWSKI","JANGIK","TIN","PAULS","DAUSSY","MARIE","ANGE","TAKIZAWA","YENYU","AU","MIYOUNG","MARCELO","R","AZEVEDO","BANNISTER","RICHARD","FUMIKO","HEZIYU","PANUPONG","KOBKHUM","TIFFANY","MO","KINOSHITA","TOSHIHIKO","TAKAO","LATOUR","TATSUYA","NOBATA","WEBSTER","SANDRA","DOREEN","TEAH","LIAN","TAK","QUI","DITZE","SILKE","LYNNE","BRADLEY","thanhtran","TAMMY","ISABELLA","RALPH","JOCHEN","OATEN","SASHA","MATSUZAKI","KUM","KWAN","N","PRATIBHA","MEHTA","ANTUNES","NHANG","MAYTHIP","SESEOUNG","KAZUYA","HIGAMI","SHIBATA","NICOLE","TIFFET","CAZEAULT","wasim","raza","MELISSA","ALEXIOU","SEOHYUN","SUNIL","MODY","MANHHA","PAK","JINWON","MOONHWAN","TEY","JAC","CHIO","VOEN","YIK","HOBIN","Azahar","Zaini","HIDETOMO","JUNGHOON","HANSEUNG","LAVAUD","STEPHANE","GERALD","YINGXI","TASATO","HYUNSEOB","KITAGAKI","YIWEN","FARIDAUS","FRIEZA","NUMSEN","KLAUS","JUERGEN","SARKAR","SOMNATH","CASSANDRA","BYEONGSOO","AlexTran","GLYKER","SUNARDI","TJHIN","vanthang","SCOBIE","LANAE","EVELYN","MUA","QING","COOK","ROBIN","STRYZHYCH","Laileng","BARBARA","JOAN","ROMANOV","NIKOLAY","TOMMY","KAZUMI","KIRIKO","SHIMIZU","CHLOE","LAWSON","KENICHI","khanhlinh","YONGGUG","AMAR","WOOHYUNG","TANNAI","YUKIO","SHENBAGAM","MANTHIRAM","LESCOT","CHANTAL","ANDR","ZXCZXC","BIRK","HERBERT","KARL","POH","ONN","EDMUND","ZHAO","XIAODONG","RUSSELL","PAVIER","LEAU","TOMIO","KEVIN","HIDEKI","TOMOHITO","ISHIMARU","KUWAHARA","MANON","AKIHITO","KOZAKI","KANNO","HIDEAKI","TAKEYUKI","SUCK","MANN","LECLERCQ","TAEWOO","CHIEH","ghj","GUY","ARAI","NAYUMI","ETSUKO","WATAUCHI","HYE","YEONG","MIAE","KAJIKAWA","LUY","WOOSEUNG","JINYI","RYBNIKOVA","LIUBOV","GICK","GEORG","BERTHOLD","DONGYUL","BALDWIN","YOOJIN","YOSHIYUKI","TOUART","ANNELI","HIROUMI","SHIMOKAWA","KIHO","WAOWEI","Nguyễn","Trần","Phương","WANGWU","ARIEL","SUSAN","LESLEY","SATSUKI","TienTran","MAMORU","NAOYUKI","CHOU","CHIUNG","AAAAAAAA","BBBBBBBB","DSSSS","NOBUTAKA","SHIKATA","TURIK","SHIM","SEUNGBO","ABE","YOSHIKAWA","TATSUO","AKIO","IVANA","BELCAKOVA","LV","BO","SONGYI","FRENDY","TIO","NILRAT","XAIVUE","KIAMOUA","JUNGKI","YOUNJEE","RENSUKE","ISHIBASHI","SEOKMYUN","LUKE","MATTHEW","ASHTON","PAI","HSUEH","SYLVIA","YIEH","QUEUCHE","SARAH","LOKE","PHOOI","SAN","SANGHEE","CHUL","HALIDA","Junji","Iwashita","HUR","YUNO","HOOKER","MATHEW","TSUBAME","HIROYA","JENKE","YUKIKO","OIKAWA","CANN","SOEUN","PHEARUN","KHOBTA","EUNYOUNG","NYUK","IMAEDA","AKIRA","AIMKIJ","NISARAT","LEGG","AMAIKE","KHUAT","YUKO","MAKIKO","OKOBA","CHAYAWAN","SHUHAINOR","ABDULLAH","HOC","MICHELLE","PRESTON","KIJAE","DIU","XUONG","TAKAJI","BONGKWUN","MYOUNG","TINA","DOOHWAN","GRANT","FOUCRIER","JEONGJU","HYUNCHUL","COLE","KIET","MYONG","DIANA","THOM","NAMSIK","JIHYEON","BRENDAN","LESTER","SAUQUILLO","OLIVER","BELFITT","NASH","ROSSLYN","MCHENERY","EIKI","KUWASAKO","GRAHAM","GRACE","MARGARET","HAROON","KHATTAK","CINDY","ANATOLY","KUZMICHEV","jisooKim","VONG","CUU","AYAKA","TAKE","Issa","Habib","PORNPAT","KAORU","OHLEN","TANCHIP","VERNO","namhoang","OHHYEON","DEBRA","ANNE","COLLARD","APICHAT","BIN","OI","WAN","KIN","LIT","KWANG","MIZUSAWA","MARCA","CEHANG","HERMAN","LOOK","THUU","MASAYA","CARMEN","FISCHGOLD","YAMASAKI","KUROKAWA","TANGUY","ICHISHIMA","ANITA","MARILYN","JONE","BUDGE","STUART","IRAHARA","ZHENG","ZEXIU","BEAU","RAVAN","GEEKIE","LAKE","MIENG","CHEONKI","YIN","XIANGYU","NHINH","MIYAZAWA","AZUSA","KATO","DANH","TSUTSUI","SOOJIN","SIK","TOMINAGA","YOSHIHIKO","SARDINA","CRESP","NOZAKI","TETSURO","YAMAMURA","ROONGRUT","WIPAN","NGOEN","MESSENGER","CARL","VERNON","RIC","GILSUN","KOZLOVA","KOSHIBA","YUHEI","VE","PHA","BUT","PINO","GONZALEZ","MISLEIDYS","INOUE","SUNMI","UENDO","KAORI","SURI","ASNIDAR","MUALIP","Lig","K","BUTLER","WANG","kwunwarat","KAWAHARA","KULLACHAT","HALL","JUNHYUK","BARRY","AUBIN","PITMAN","KURNIAWAN","WINOTO","DOLMATOV","VLADIMIR","MUSNI","NESTOR","PONGASE","DANGLANH","MILLER","DONNELLY","IKEHATA","TAKESHI","SAWASHIJI","JUMPEI","UJIHARA","HELI","AAAB","EER","SOMRUG","LYU","JINHONG","MINGI","MAO","JIANQIANG","BIRYUKOVA","ANASTASIA","MARINA","MAIKO","SAKATA","KIYOSHIGE","VOLL","HANAKO","WOODGATE","GAI","ARTHUR","HYUCK","MORIE","PIWAT","WAKITA","RYOICHI","UENO","NIIMI","TOO","FAY","ON","TI","Xuyen","LYON","KYUNGHWI","NISHIHARA","AKINORI","SIG","EUNKYUNG","GAYOUNG","BAIK","DAKYUNG","VIRGILIO","ABAD","SEKIYA","INHYE","WOOK","NAOTSUGU","HAIROYUKI","YAN","MEI","YUTA","SAKAKI","SEGIRI","MASAHISA","HU","LAIYIN","Myeong","JEOUNGSIK","KURIMOTO","TEAK","SERGEY","KANEMARU","JATURIT","OMIYA","TOSHIHISA","OKADA","MINOBU","TAKEUCHI","SAKAI","HIRONORI","SIAN","KARIN","KLOESS","HYEYEON","AIZAT","JAINI","FUJIWARA","TAKESHIMA","JUNKO","NAKASHITA","Volker","Fuerderer","MIWA","NOBUKO","NONOA","SHEAU","LIAO","HILO","SLUTZKY","FELISA","GILDA","LINE","HOAT","MOMOKA","HORI","NGUON","KAIHUA","NISHIJIMA","HARUHIKO","PEIJING","BOUGHEN","SAITO","KOHEI","SZE","ELSA","FUJIMORI","SHAO","DOHWAN","KAZUAKI","KANAMOTO","SEIJUN","HYUNGSEOK","SUL","DONGHO","ZALITANON","SHATCHAI","YUSUKE","GGYUN","NHIEP","RIANCHAI","THAT","UG","GRAS","TRISTAN","NAKATO","TREVOR","DENMAN","SEONGKU","THOAN","HIRATSUKA","MIKYUNG","NIKLAS","WILMKING","GONG","HYEJIN","SWICKARD","JOSIAH","NISHIKAWA","LAUDE","SEVERINE","GAUTIER","ARMELLE","MIRABELLE","YASUAKI","HIRAI","SOKIRKA","OLENA","MINHAE","NAYEON","KIAN","KIUNG","SIONG","ZHU","QILIN","YADONG","CHAWLA","RAJEEV","DANHNAM","MISHKIN","IGOR","NHIEM","KATSUHIDE","YOHHEI","JIHUN","NOBUYUKI","nhatkhanh","Kenneth","Hogan","KATSUYA","NUTHUYMY","RINTARO","HSIU","MAENO","KOTARO","Moffat","OKAMOTO","MAMIKO","ZAIN","BADRUL","MUNIR","CRUZ","LEA","HAYAMI","NARUYA","YOUNGKYU","MULLIGAN","VEJPONGSA","EKACHAI","MASAZUMI","HAGIWARA","AKIKO","XIAOQIANG","CHIAN","YAMANAKA","SHINICHI","KEIJIRO","ISHIMI","SUJONG","SUHYUN","KYUNGTAE","MINJEONG","AKIMOTO","TERUHIKO","NING","ANDRIA","BECK","KATRINA","ONO","YASUSHI","HAMAMURA","ZI","AUDREY","CHRISTIAN","BERG","MATISSE","CH","NANG","RUONG","JAEHWA","Sangchan","SETSUYO","BASRI","HAWA","ITSUMI","EVGENII","MITSUNAKA","Dunseath","SLAVIN","VISHAL","AGARWAL","XUAT","JIYU","THOAI","KANON","MISAKA","MOINE","SEBASTIEN","VALERIU","ARTENI","KANNYA","RAJAN","SUKHANI","MUKUL","AJAYKUMAR","TAKAYAMA","ANFINSON","BOUNMY","DONGSUN","SHAIFUL","AMRIN","KARIM","YEONWOO","ZHI","YONGWOOK","TOMOYA","KAWABATA","MOHYUN","ZAHARI","MUIIN","PAMELA","FLUX","WATASE","BUM","MIRA","KULKARNI","NATASHA","ASHOK","SAURABH","TANDON","JOONSUH","GIM","SEONGHUI","SANJO","TOSHIHIRO","KINAMI","YUICHI","BEATRICE","QU","NAKAJIMA","DONGBIN","LUTFI","HAFIFI","JAP","TSUJIMURA","CAI","ZHENNI","ENDO","MISAKO","EDIONG","VIMI","ASTRID","TSE","DONGUNG","SEAN","HINCHEY","SUHEE","KYUNGUK","PIRAPHOL","DONGJIN","ADAM","FLINTER","SOREN","HUSTED","LANDERT","ARMIN","KONRAD","GUIDO","LOPEZ","AGUSTIN","AB","OKUMA","YONGDAE","SUNGJAE","NAYOUNG","HIKOSAKA","MASAKO","MALIANA","BINTI","ISMAIL","BORAM","YO","HWAN","JEEHYE","CHUYEN","ASAKO","SHINDO","SETSUKO","KWONG","NHAM","YOUNGDONG","SATORU","DACCHI","SUNAH","SEYA","DER","PUTTEN","VICTORIA","KAR","HARADA","TEKESHI","SAIN","FERN","SHUQI","TOKOSHIMA","NAKAGAWA","YEUNG","GORYACHEV","KLOTH","SUNGHEE","HIDEYA","KURAKATA","MARIN","INTA","YOUNGHOON","KUN","EMILY","SOYOUNG","KNOWLING","TANH","YOUNGA","GEUNHYEOK","JINSEOB","KIRIYAMA","YURIKO","MIKE","RAINER","TIET","KARPOVA","BOBB","ALLAN","ROSALINA","ORTIZ","NAOTAKA","Peixuen","FEI","JEONGEUN","UCHIDA","HARUHISA","KASHIWAI","JUNGHO","GEK","SUSUMU","DAEYN","WANFAN","MICHIO","YAMAGUCHI","TAKEO","KUDO","MITSUYUKI","JENSSEN","JEREMIE","HONGNG","DEBELIC","NIKOLA","XIT","HWANWON","MEE","SYED","HASSAN","MANIKU","SHAFEE","AFONKINA","JUWON","DONGHWAN","KAMBE","KENYA","TY","STEPHENS","NAKAGAMI","MCKANE","RUDIGER","ZAMINDAR","TAUFIQ","KURNIADI","RUDY","SEOYOON","ATSUSHI","KURATA","KATAOKA","CHEONG","KOSUGA","MITSUO","KAMEYAMA","KUMADA","MRS","BULL","YOUNGKYUN","KHOR","VANTINH","JUNGSUN","YUNYU","SANGJUN","QIANG","ODA","TOMONORI","KEN","KAJIWARA","HY","POESL","Asran","Affendi","TIENNHA","LUCA","TSUNG","UCHINO","STEVEN","HYOIN","HEUNG","CA","TATSUHIKO","WOONG","SURIANA","HANI","RAMAEL","KUEN","SHINGO","ATOJI","Pisal","HUYQUOC","NAGASHIMA","MIKA","PAPKO","GOSEKI","JEOUNG","HUN","LAMBIE","XIE","SHUSEI","YOHANA","KRISTANTI","SHUZO","JINGU","KOSHINO","HISAO","HOMMA","SEUNGYEON","MUNG","TOLU","WAYNE","SIATAGA","WAIMIN","XI","THIEP","YASUHIDE","XIU","SANGJIN","MINEO","EMMEI","PERJUMA","LEPAR","SONYA","KIRSTINE","HENDERSON","RYOKO","HAUFE","TEZUKA","Gilles","SEGRET","TASAKI","TERESA","PATRICIA","LISS","ASHIDA","MUROYA","ELLIOTT","ALMOND","RIDLEY","TERUKO","NAGASAWA","YOSHIHIDE","OSADA","GIBSON","JOSH","BREIER","MUKESH","BHARWANI","ALEXEY","BUHTA","MICHEL","DAISUKE","KOYAMA","STIG","MAGNE","LAMBERTO","AGAPAY","PUBLICO","MCDILL","MELANIE","PHIEN","TADAHIRO","MINHHUYEN","HIDENOBU","XINWEI","ELISABETA","JOCSON","ZORILLA","VALENTINA","OSOKINA","OTA","KIRWAN","SALINA","SUESAT","ARTEM","SHOSAKU","MARJORIE","FRANK","MANHHOANG","HELENA","POSADAS","LINDA","OBRIEN","ISEZAKI","TUANNGOC","GLENDA","HONGPHUC","TOT","KUNIHIKO","JEN","MATSUO","KELVIN","HSIEN","JUNGWOOK","GRARD","WENLUNG","YEH","TOM","KOLDER","TERENCE","FOO","VIRA","DIDYK","MORIYO","MINAKUCHI","SHENGXIAN","YONEDA","EVERITT","JONGCHUL","VOYTUSIK","SEUNGHUN","MIKIO","IDETA","NUONG","MORIMOTO","JAROMIR","LANG","TORSTEN","ANGENENDT","KHAN","HUGHAN","RAY","VINCE","NAHO","RENDLE","TRACY","FRANSSEN","MCWHIRTER","ISAAX","LOZANO","JAZZ","FOY","MCDONAGH","VANHUY","KURUVITA","KAYOKO","NOZUKA","JOHNSTON","SHOONG","NAPATORN","NUCHNOY","CORNELIUS","MULDER","HELENE","CHEVASSU","DUCCUONG","WOOD","ANNELISE","HANSEN","THANHTUNG","PINGMU","KOKICHI","NESATO","MOTSAVAGE","RAMUNE","ARLAUSKAS","NADIA","TOCCHET","SMUTNY","ONISHI","EUNSOOK","QUANGTHU","OWEN","HOUSTON","VUGAR","SASAI","YUKIE","SAWYER","TAKAISHI","HIDEYOSHI","CHRISTOPH","SCHEIBERT","CARIN","HOLROYD","MASAMICHI","IKEDA","VYVIAN","NATSUKO","MIZUSHIMA","ARMAN","AUZHANOV","NARAYAN","ALEXEI","SIBIRKIN","MORIN","REEVES","CHEAK","KEONG","HARAKE","KUBOTA","THANAPON","XUANTHUY","NGFOC","GISLENE","VALADARES","VINATZER","CHICHENG","RAO","SANTA","MINHCHAU","VARAPAT","FURUICHI","EVGENY","YARKOV","SHIMODA","RAJESH","LAWRENCE","ZHONGYI","QIAN","THIPHUONG","BATTLE","NIESJE","ELISABETH","KOORNNEEF","MARINUS","UIJLEN","SAYURI","NISHIMURA","CRANE","MEIJDE","THIYEM","INHYUK","SOPHIE","MORESTIN","CADET","HYANGMI","KOYUKI","OKU","TIENNGON","ALOUN","BOUTSADY","YASUKO","BASSO","EVANS","IMELDA","REIKO","NELE","DEWILDE","HIDEKO","MANHHUNG","HAMID","BADRE","PIETERS","SECHEOL","CASTEELE","SOUSA","KURINISHI","SUYAMA","AGNES","DAUBRY","ANOLOTH","YOUNGSEOK","LILIANA","URENA","NGAU","SHINTAROU","IHAR","PLESKUNOU","FATIMA","BEGUE","ANDY","JUNYUK","JEEWOOK","THIU","BYUNGCHO","ROSALIA","KERN","HUNGCUONG","UCHIKO","MATTIAS","LARSSON","JOONG","CAU","YE","WHITE","TATCHUNG","AMELIE","GILBERT","MALLET","BEN","BENNY","FOK","NICOLAS","VORUSHKIN","CHRISTINE","SABAPATHY","AURELIEN","CHAZEL","WEHOFER","VITHY","EUNKOO","EIJI","SUER","COMMAUX","MCCONKEY","CATHERINE","DUONGCAP","TEYMOUR","SUNDERJI","ATSUYO","KUNIHIRO","CHUAN","KINUKO","ALISON","RATCLIFFE","HONGANH","ENRIQUE","SEBASTIAN","LEDUNG","MERETE","CHIKUDA","PATEIRO","FERNANDEZ","FROST","TSUNEO","GOHDA","BAUCHE","ANGELO","GALLO","JER","HORNG","MICAH","WALKER","SMYTH","TRIBES","MONTE","FARQUHAR","KONGSIK","CHAO","ASANO","GAUTHIER","VERDON","KUANCHANG","XU","LIANHUA","MUI","HAMBIDGE","SATAKE","GEZART","KYUNGJIN","SHUNICHI","KUBO","DUONGNAM","MASICA","YUE","DOO","PHILIP","TAULELEI","SIIRI","BENNETT","ATSUYUKI","STEFAN","ROLF","VERAWATI","CHERYL","DONOVAN","CLAUDE","ROUSSEL","SEAH","SRDJAN","RISTIC","NORIKAZU","KAWAI","THOMPSON","CHERRY","DEL","VALLE","TORRADO","DOWD","HONGVAN","IROHA","JENKINS","LAUREN","WALLACE","JINWOOK","BAS","MANDERS","HANNA","TAKEMOTO","NIREI","ENGEL","KHENG","JOE","DORIS","LEONID","HATSUOKA","CHARLIE","TOU","CHIAMEI","TSUILIU","ISABELLE","THELEN","VANTUONG","ANDREJS","NANCY","ROMANO","MISUN","BOHLER","GIRISH","GOVINDAN","ELINE","HET","HOF","WEITE","QAUNG","WQE","WQEQW","OPRAH","KOIZUMI","KARIYA","HARA","KEVAN","TERMOZ","DIEGO","ROSA","SARA","ELLIS","CORALIE","POULLAIN","NEEL","JUDITH","SPICER","KANAI","JULIAN","KNIGHT","YOKOTA","HYEMI","ASAYA","KHINH","SUDER","HYOUNG","CHITHUC","JUNGA","DAEKYU","WICHAI","PITEAUD","ZOE","BUTT","ISOBE","FUKUDA","XAVIER","CAT","DMITRIY","SPEKTOR","GIOI","LAO","LESLIE","TIMMY","EUNJUNG","HEONG","KAHO","TOBIAS","KATZ","THICUC","GYUI","YVONNE","ALEXIS","LAURALYNN","STEFUREAK","GRABHAM","CHRIS","BRIDESON","ADCOCK","ELVIRA","KARIMOVA","MIYOKO","HAMBA","INN","TIONG","PLOOG","MINA","YARIUCHI","YOSHIFUMI","MASAHARU","KURASHINA","VANESSA","KIMBERLY","BERTENS","CHRISTA","KUOCHING","TAKUHITO","TSUJITA","KEUN","FOX","PRASIT","CAROLINE","GUERIN","TAKAHIDE","DAEBEOM","MAENG","NEWMAN","NGUYENHUU","THANHPHAT","TOMIYAMA","GUAT","BERNARD","KEITH","ANHKIET","SHOZO","ANESARI","KIL","SOMESH","DAYAL","IKEGUCHI","TSUCHIYA","SEUNGWOO","CHOUNG","VANA","DALIWAG","KYOUNGHO","CHA","SHAHZAIB","AKRAM","XIAONING","SIPING","SIAO","LOE","TEXIER","FLAVIO","MARTINS","RIBEIRO","GORDON","JF","TIANYE","GU","AK","WINCH","MICHAL","SILHAVY","WARD","THUTUNG","BUN","RITH","SUON","PHENRUNG","BEYNON","LAND","TEISHA","MOTT","KRAJEWSKI","NAGAKURA","YOSHIKAZU","MARLA","MITELMAN","ROLAND","CHANET","GRETHE","NATHAEL","DUBOC","DAE","IRENA","ROMANOVA","HYENG","MASAKI","TANABE","KAZUHIKO","KAGAWA","LYNDA","LETHUY","PHAMLEE","ATKINS","YIHSUAN","MIZUSAKI","SHARNI","BURGE","PERSSON","PYUN","JONGSIK","ELMA","GESCHIERE","MICHELE","DAUPHIN","SHOKO","OHIDE","CHARLES","DULEY","WILLIAMS","ANGELA","ANILA","MARY","NOBUO","SHINOHARA","DEVAUX","JARRELL","CHIL","ALEKSANDR","CLAIRE","LYNN","REYES","MAYUMI","SHIMOTAI","XUANCAM","KANAKO","CHATANI","WINTER","YANAN","AKSHAEV","POPOV","SEAK","WOON","CHAIWAT","VETRANO","KOGAN","HSUNT","GRSER","KERRYN","HUGHES","RACHEL","GUILLARME","THILIEN","SEUNGHWA","HUH","PICHET","TAYLOR","SUE","COPE","FOUCHE","WESTMORE","ESTRELIA","DIAZ","OHMOTO","HYEHYUNG","ALEXSANDR","GULYAEV","AUBOYER","TAODA","SHUHEI","GABRIELA","MAKIUCHI","DINHTHIEN","MAKAROVA","TEE","LIP","SLEPTSOV","KIEUHUONG","YUJUNG","TEO","MALIKA","LABGUIRA","MARYSE","JOCELYN","BASMAYOR","VERSOZA","JORN","BACKES","YUMOTO","HIDEMITU","KATAYAMA","KEI","WEBER","ANNIE","NISHIMOTO","TIMUR","MEDVEDEV","ADRIAN","TAMPLIN","TIKHONOVA","SVEN","BAETEN","YIU","BATHIEP","BOROVKOV","PASCALINE","WYDAUW","TOBITA","GLENN","ZUTPHEN","SIM","MIZUKI","TRAMOND","CHADBONE","ANJALI","RIGINA","BOYACI","BELYAK","JONGHYUNC","BEWLEY","SHANGYU","DENIS","ANDRIUNAS","STURGEON","BEVAN","ALVEY","WAANQ","SHAANQ","LINDSAY","MCINTOSH","EMILIO","SUNAZAWA","DINHVINH","CHYONG","SHEVALDIN","GAY","TSUI","HASLER","BILAN","MARCO","KUEPPERS","SLYSH","MARIKO","MIYATA","SHIU","JULIET","MILLS","RUSTAM","ISMAGILOV","MARZII","NANRI","SUGIYAMA","LEILA","HIDEHIRO","DICKSON","SUNGSOO","ALESYA","ALFONSO","LOBILLO","LAZAREV","HUUTRONG","MAURIZIO","DELIA","VERMEULEN","ANNILYN","KATIGBAK","TERJESEN","BAJOU","JACOVICH","BUCHHEIT","MATHILDE","WARGNIER","GERHARD","SCHMIDT","ILHOON","KARINA","DUCQUANG","KRISTIEN","STRAGIER","XUN","RUDNICKI","CANG","HIGO","MATVEEVA","MERI","KINNERET","FRIEDMAN","PENNA","ARAM","TAKANORI","YAMASE","YOUNGDAI","JIAOJIE","GENG","YOSHITERU","FUYUKA","IIJIMA","PINYU","EFREMOVA","JOHAGJE","BYUNGWOO","EUNKYU","STIGLER","BOHYUN","JACKY","HOFFMAN","STOCKI","RIGGS","WOLFF","SHOHEI","FRANCESC","PUIG","PERO","NATALYA","JEREMIAH","KENNAN","HASNAA","BINEBINE","HARDER","LYDIE","PROSPER","FREIXES","LENNART","MEYERSAND","TIPHAINE","FIHEY","PELDUNAS","SUZANNE","WATT","JANDEL","HAIGH","SAYANTAN","GUHA","CHANYOUNG","HAGU","TOMAS","ALEJANDRO","OYUELA","MAR","SEEUN","MICHIKO","JOYCE","YOOHYUN","CONNELL","MALONEY","YASUMASA","AKIMOVA","EMMANUEL","LYN","ANTONIO","SOTO","FREDERICK","RANKIN","CHAOYUNG","KELLY","BREGANTIC","TOSHINOBU","DARRYL","JOBSON","HELEN","HYSTAD","TEDDY","HECQUET","HUUCI","MORRIS","RUDDICK","SIPKE","LITTOOIJ","YUSCHIK","NASIM","ALIMOV","MAIHUONG","SIGMUND","MYTTING","LIANA","ARENA","GREEN","CHARLYNAM","MASAHIDE","HOO","TII","MEERBEECK","TONY","BONNICI","SANGKAP","EDOUARD","OISHI","DUNGTRUNG","JENS","RICHERS","VARVARA","EGOROVA","GIYOON","LOCKLEY","ZHE","IULIIA","SAVYCH","SONGHEE","KUWAYAMA","CASSERLY","PAULA","GAVINS","COUSINEAU","MARLOW","BARRE","RAVIDEEP","GILL","MUNEYUKI","HATAE","JOZSEFNE","YONGCHUN","KIRISAKI","CARLA","CARESTIA","JONGHYUN","WOOCHUL","LEANNE","BUCHANAN","PAULETTE","MERCIER","KREUSCH","LEESA","FERRERO","GUG","EPOUSE","YAFANG","SUGANUMA","KAAJAL","SINGH","FANGOO","KYUONG","SANO","JULES","GRINNELL","TZVETA","SIMEONOVA","RAHUL","VIENMINH","BALARD","YENG","DUIJFF","YAU","ERICH","LANGE","MEENAKSHI","BLANCHARD","KYOICHIRO","FENGCHIA","BEAVIS","WEIBI","HING","GRIGORYEV","RYAN","MK","CLIFFORD","NELSON","HEINEN","PIETER","WINDT","SUNGMIN","CHAE","COURTNEY","FIELD","BOJEONG","SHIGA","WERNER","KENT","SCOTT","CHULMAN","HENRI","BETTY","BETI","THANHTHUY","KWANGMOON","SHIPULINA","RUTH","WEILINGER","DOBES","SOPHA","BARNES","WOODING","YVAN","GIRAUD","KOSUGI","POLYAKOV","KUI","CHRISTELE","JENNY","LM","SMET","GALLAGHER","JAI","PATEL","JUGNET","BAILEY","LILI","YOUNGAE","JIKYUNG","HYUNJONG","WOODWARD","PLASHINOV","JUNE","BAYARD","EDUARDO","TEJADA","SANCHO","KWAK","DOUGALS","SAULSBURY","MINHSON","ILYA","PRUE","NORMAN","CASTLES","TADA","SIZAREV","SITHU","SHAOMIN","ILONA","DYACHENKO","MCDONNELL","RONG","OGUNDIPE","BRANDON","KASHIMURA","LIJIE","NGUEN","ZUNG","YUKAI","ANNABEL","ALICE","CLIFT","GINO","BONETTI","SWAN","SINA","SCHWARZ","FENGGUO","HAAS","CE","RA","LIMIN","STECHR","MARYNA","DEN","TUTHO","TEOH","TOMOTAKE","NANFENG","VICKERS","FUI","CHEW","HYUNGKUK","HEALEY","DEMIANOFF","JEESUN","MIJIN","YAGO","PEREZ","TRUNGDUNG","YUKITSUGU","TABATA","YOUGA","TRANTRUNG","HATA","NOBUYO","DINHBANG","NINA","EVELY","SEHOON","KARINE","GUCIK","ALVARO","MUCIDA","HANWOO","CHOO","BANDYHUI","AMANDA","CHULHA","FINN","MICHIHATA","HIROMASA","KURODA","JENE","RHEE","HANA","COATES","NAVY","KOUMPHOL","IWASAKI","SUNGIN","ANALISSA","SINGSON","WAGNER","ULRICH","KOLNIK","CHAYOUNG","HANN","HURST","KIRAN","CHIMA","LABELLE","YOUME","HANSOL","HAHM","TAILIANG","O","KYLIE","ZAYTSEVA","JUSSI","KUKKULA","WOLF","MARION","NAMAKONOV","JENNINGS","TARO","LENA","BOLSTER","YUM","SHING","SHUM","THORNTON","VIETAN","ZHUOPEI","SEABY","TORET","EPIFANOV","CLIVE","ALBERT","SANDOVAL","NATHALIE","SHINOBU","JEANLOUP","BASSET","TRACEY","JONES","HUNGTRINH","TANI","BELL","MARI","GRUDININ","MUHWA","TOSPORN","NGOCCHI","TROYANO","MAKINO","PIOTR","KRAWCZYK","GIAM","MHARRA","MESA","TOMOHISA","KURITA","BYUNGSOON","BERGA","LUIS","FUMIO","FUCHI","NANAKO","MIZUNO","SOPHIA","ULYSSES","ESPADERO","NIELS","STEGEMAN","JULIA","KUMAGAI","STANTON","HENRIQUE","BRAGA","PICHAI","YUEH","XIAO","LUCY","BEAL","OLIKER","FRIEDLAND","MUSSHI","WESTBROOK","HERMANN","KEPLINGER","LIPPMAN","YAMABE","CLARE","EDMOND","JUNGHWAN","ALEXANDR","ABAEV","BLYTH","PREMYSL","SIXTA","SHINYA","KAWAMURA","BASILE","HERVIEU","HONGTHAI","DORNAN","KASIDIT","THONGPLEW","MEIYU","TOLLETT","TWITCHEN","YOSHIWARA","PRAMI","LARSEN","PATRIC","ELDER","YALING","CLAUS","TOMOMI","MONIQUE","BADIH","SATOMI","ZHIQIANG","BRETT","REINERT","AURELIE","GERMAIN","EM","TIETJEN","ROSIORU","ROSS","SHEERIN","XIAOBIN","MARTIAL","BUISSON","MCLEAN","MINEKO","ROYER","MIYEUN","PANKHAE","LUDOVINA","BALICANOT","ANATOLIY","TERESCHUK","BLANCHET","VERONIQUE","THONGBAI","MOGA","TOMASZ","TARASOVA","KATHY","IMAI","GODDARD","HIROE","URANO","HOAC","ORCUTT","SLOANE","LEONARD","YOUNGTAK","NARISSADA","IVAN","GONCALVES","PINTO","JR","SOPHEAKNA","GOY","SERGIO","HERVAS","CIFUENTES","MOSSIE","JASMINE","BRABANT","CHIRADEJ","MITSUKO","GERO","MERTENS","JONGKAB","NGOCMINH","LOIC","NGOVAN","IWAMOTO","THUYMY","GARNIER","GULTYAEV","CHIEM","HUANCHEN","KAZUMASA","KAMIGUCHI","INHEE","DAP","ALEXANDRE","BOUCHET","TOYOKO","SHENGYING","MAILYNN","ABEL","MICHENER","AIPING","DAVYD","DAVYDOV","NADEZDA","CHUSOVA","TRANTHI","TAKETO","BYONGIL","TUYETHANH","GIUSEPPE","BARBARINO","HARTSTEIN","CHOMPUNUJ","GPCAPT","ISSARAY","SEDER","BRIGITTE","LLOYD","EWA","NAOTO","OBATA","NUBUKO","LARCY","MONTI","SOLDATOVA","XIAOLONG","JULIE","FOUCHER","XIAOLING","LYUDMILA","GANEEVA","RUIBO","NGUNG","BOUGNOUX","SANTANU","TUTIEN","BROWN","TOSHIYA","MIYUKI","ELENE","CORINNE","GUILLOU","JEANLUC","SALLY","MERLETTE","MET","SANGBONG","TATIANA","JACQUES","RYASOVA","KANNIKAR","PINPOUNG","ROMAN","KUMIKO","SHIMAKURA","FIONA","FLINTAN","XE","HOLLER","ERWIN","TAVERDET","BLANDINE","ITAY","MEHL","MARTIJN","GROOT","KING","FILIPPO","MATTIA","GINANNI","LAURANT","JULIEN","MENU","THIDAO","SUZAKI","SCHEGLOV","TAWEEYOD","ICHIKO","TAKATOSHI","YAGISAWA","NAOKI","KEUNHYUNG","INAEE","FURUKAWA","TOHONG","PIERCE","BEOM","MICK","BALL","EUNSOL","MCCAFFERY","BACKMAN","WILHELMUS","CHRISTI","IKAEV","VLASOV","ISHIZAKA","HIDAKA","DEOK","TOKUDA","LAC","KNAPP","CONROY","ABRAMOVA","SEBASTIA","GARRETA","GRAU","ELEONORA","MERJANOVA","JIAQI","LINGLING","MASAHIKO","NAMI","TSURUYA","RIN","BINNS","HYUNWOONG","GIL","DEP","TOKUI","JULIETTE","DONCKER","JINXIAO","HUITING","ACHARAWAN","SURAKOSIT","YOSHINOBU","IHARA","MARIANA","KOLESNIK","TROND","HANESAND","HUYENANH","FUMITAKE","LANGHEIN","KEAN","SAP","SUMIN","NGOCANH","SARANYA","LAYTIKUN","FRESNEAU","POSSAMAI","CHONGZAN","LEVCHENKO","RYALL","MOCHET","DHIRENDRA","SHARMA","KIYOTAKA","NAKATSUKA","BONHOURE","ROBYN","JOYE","HARDING","DONALD","HUNTJENS","TAKAYUKI","HEN","MINEEV","FUKADA","HYOSUN","VYRATH","KIMDUNG","NGUYENTHI","PABLO","HOPE","MAGNUS","BOKHEE","JARNO","LAKKALA","KIEKO","NHIN","LASAPAN","YEONGGYOO","JUIHSUN","EDITHA","BANCALE","HYUNJUN","CHUNGIL","NADEZHDA","RAFFERTY","NISAKORN","MANFRED","YANNICK","AUBERT","DIEMTRANG","JUNHAO","CARSTEN","RATH","SHIMPEI","CHIHARA","BOCHKOV","YUU","KJELL","ERIK","POOLEN","PANDORA","SANDVAND","LYKHINA","AYAMI","MUKOYAMA","MIKHAIL","MOROZOV","KANKANOK","SUGOSOL","SPICHAK","QIN","ERNI","DUYN","HEIDI","KIRRILLY","ALTERATOR","RUCH","EMERSON","GARNIEL","KENNY","KAM","SING","YASUHIKO","AKASAKA","MCATEER","STAFF","AITKEN","RYOMA","YAMAKI","ILIANG","FRANS","BROERS","YOUNGDOO","HAM","YONGHYEOK","BYEON","KUNIMI","NYUWA","YUKIYASU","NAKASHIMA","ANDRES","CONTRERAS","DEMIDOV","BOLING","ADELINE","VIALLE","BRAMICH","MACKINNON","MARC","HANDELMN","RENAUD","IBORRA","DINHKHANH","MYLENE","BOUCHARD","FLAVIA","BREU","KOBLER","VIOLAINE","DEVENS","JEONGYUN","JEROEN","JANSZOON","STOL","RICHART","ASUKA","SAKOO","KNUDSEN","IB","EJNAR","RYUTA","LEJOSNE","EVGENIY","ZVEREV","LEAH","POPE","MADDALENA","FIORIELLO","MASSIMO","DELLA","ROCCA","HINH","OWAIS","SHARAQ","WAHL","TOSHIHARU","LUCHETTI","RATCHANEE","KIMIO","IIDA","CHIAHUA","BUNDIM","DWIGHT","CONWAY","TAEBEOM","MAURICE","CHAOYANG","ALEXA","PICCIONE","TRONGHUY","F","GARTLAND","MARIANNE","LATYSHEVA","PER","RASMUSSEN","KRAGH","THANHAN","SENGTHONG","PENCHUN","IAMCHUM","KOICHIRO","KETMIEN","PHE","ATABAK","VALIVAND","DUCANH","GEORGE","VEALE","KAMEI","BAPTIST","KERR","LANGLEY","PERER","NAKAMUKI","GINLEY","SACHSE","STANISLAV","KOZLOV","INSIC","SEONGJONG","FABIENNE","BILLET","JORY","MIKIKO","SAERYEO","MASANORI","FOMIN","SHEW","JAEHAK","SENGCHAN","DELPERIER","LAKSHMAN","PEIRIS","YOSHIMITU","TURGEON","ANDREY","DROZDOV","PANIDA","CHAROTOK","BERNARDI","ADISAK","KOMINAMI","LUCIENNE","KWANGSE","MEYONGBAE","ILJOON","YASUI","MORTEN","MAGNUSSEN","GI","KANEGAE","CHINPO","CHE","ANODO","QUOI","VASILIY","YAKOVLEV","LAURA","ZHUANG","NAHYUN","PHILLIPS","ANTONETTE","VALENTIN","DAUCHOT","KIA","THANHTHAO","HOJNATZKI","THANHDUC","ETIENNE","COLETTE","SCHAEFFER","SOLODOV","DIRK","LAMBERTS","BATEUP","YUICHIRO","ACKERMAN","KOON","TEH","TANIGUCHI","VIKTOR","SCHMIEDER","JAEDOO","YOU","AT","SUNGHO","BERTRAND","VOLLE","JOAQUIN","AGUILERA","KAZUTAKA","HAYAKAWA","SOBLE","TOK","LOGAN","OSHIKA","MINHDUONG","EE","RENUCCI","YUEQIANG","OSHITA","XUE","BANCROFT","JE","KAZUKO","JAEWON","KRIENGSAK","MOTOHIKO","FUKUNAGA","KAREN","STIPP","HOOFNAGLE","MORIKAMI","HEIENKUN","SWARTZ","WOLFSTIEG","JOHNSON","JAYOUNG","CRESSWELL","PHAMVAN","SAKINA","MASALEC","KENNEDY","THITHAM","TRANNHU","SHE","GREVTSOVA","JOYCELYN","POETZ","KHOANG","FRASER","SEHYUK","SAGI","BARRERA","ANTIPOV","YEONGSU","NADJA","ANDRAD","VANQUE","SYLVIE","BOUBEL","YUYA","TUAT","ERIKA","GARBRECHT","XIAOMING","VYDUMLEV","OKI","KARLO","STEFANO","DOMONDON","PASKHIN","DANGHUNG","BURDEN","EKANAYAKE","NANDANA","BARBY","GARRY","NEVILLE","CALEB","ZHELEZNOV","THANHBINH","LEVANKIEU","KATSUHITO","HIRAYAMA","NI","BENSON","CONGTAN","TSUCHIDA","SEOKKYUN","KYUNGJOO","SUH","KIENNAM","YONGBAE","TABETA","GUISUN","MARIKE","GOENEE","MCARLEY","NIRACHA","SEEHATONG","CHIKAKO","GIORGIO","PUNZO","EDWARDS","KARI","WATSON","JUNYONG","HUBER","BUCKALEW","NIL","YONETANI","MEDVEDEVA","WONYOUNG","COLLINS","RYO","NAMKYUN","HIROAKI","OKUYAMA","KOMODA","YUMI","ENOMOTO","AKEMI","KIYO","ROKUTANDA","SEON","THIHIEN","TERRANCE","ODEAN","NIEKERK","SHELTON","DROZARIO","GAYNOR","DUYTUYET","SPAIN","GO","FUKUCHI","TAKAHISA","KYOUNGMU","FENGLAN","NGOCGIANG","HEAN","DING","GINNY","LESHKOVA","ABBOTT","RODRIGO","VITELLI","IULIO","FRANCO","ROBERTS","TOYA","PHO","CHEAN","TABITHA","ARINELL","DUFOUR","NISHANT","GARG","ZHIHUI","NISHIWAKI","HONGHANH","BOGOMOLOV","DUCKJEEN","MURACA","HSUN","HOANHHUY","VEARNALS","MORI","KUNIE","GIANGKIEN","BOROSKI","POSPELOVA","MIO","KAMITANI","JACKSON","JIANHUA","BAI","NGOCQUYEN","IDOIA","I","GIRO","KASUGAI","GENTAKU","GOTO","XIN","MAURO","CATTARIN","VITALY","SKVORTSOV","QUANGHIEU","ANATOEY","KUTOVOY","JESUS","RODRIGUEZ","ORDI","CHOONG","CUA","SILVA","CHINGWEI","IRYNA","CORSINI","MABELLE","LADOUCEUR","SIOBHAN","BAXTER","OLAV","RONY","BASSOUL","BRYAN","MORRELL","ROWE","GAGEY","PAVEL","LEONOV","FALKENAU","HORST","DUBIELLA","BRUNO","LUCIA","HSINTZU","YAO","MYUNG","RYOH","TERAWONG","KINUYO","TASHIKO","KIDO","KLIMM","PARR","IKEGAMI","SHIHOMI","KOMURO","YUANYUAN","CAROL","EVGENIYA","LEONOVA","YOULDEN","AIME","METHI","VONGSAY","FABRICE","TRILLAUD","KESAVAN","NAIR","SUBHASH","HUYNHTAM","TR","GRENIER","SAWADA","SEMPLINER","EINAR","NEGAARD","TOI","YOUNGMIN","JAECHUL","HIDESHI","SALAM","ALEXANDRA","KIOCHOU","CANALE","WARWICK","TURNER","IMIN","FULING","JENNET","SAMBOUR","BENTON","SONDRA","GRATES","STEWART","SONY","PRUNIER","NATALIE","ILKIW","AVERY","WATTERS","THATCHER","MARCONA","SIDOROVA","HYEIN","ESLAKE","KAZUSHI","ANHTUYET","TATSUHIDE","NAKANE","RUAN","SHIMOHARA","MINJUNG","NAGASAKI","MAXWELL","JENCKS","SUNYOUNG","KARYN","HIRIMOTO","EDWIN","CARLOW","COSBY","HUYHOANG","LIFAN","NORA","CHARON","VANCHAU","WONSUK","MATSUDA","PETTITT","HORIGUCHI","JUNWOONG","VILCHEZ","GUIVARCH","NOBUMITSU","OGINO","MINAGAWA","NIEVES","NTALTA","KURATATE","ANTONIN","HSIAO","KAIBE","NGOCTHUY","NORMA","RAMI","GHARZ","EDDINE","TYLER","GEORGES","COQUEBLIN","BECVAROV","CLYDE","SEOW","JANING","RAVIV","LARS","GINSTRUP","NAO","SHIMADA","ZEVAKHIN","OZAWA","MIZUE","AOYAGI","MIAG","EMERI","SEONGSOO","NISHI","GOLOVACH","EDMUNDS","LANDAT","ROSALIE","XIAOXIA","KUKUCKA","VANHUAN","CASONI","CLAUDIA","CHOY","MARUO","SRI","BANON","WIJAYANTI","ZHIGUNOV","ALINA","YURYEVA","CHUNLIN","DANIELE","PERRONE","HUDDLE","THANADACH","NANSUP","QUYNHMAI","REUMER","JOSHUA","OLKEN","OLEGUNNAR","GALL","JUNFEI","HAIYEN","HYUK","HOSNG","NOZAWA","ZHMIDA","MINHO","FRANCOISE","TUBIANA","BENEDICT","NABONG","SOJI","DIN","DYK","FEDOTOVA","LINA","NIEM","KAEDE","CHUENHUEY","CHENGCHE","THERESA","MARIAN","SALIE","YATAI","STEVENS","TARRANT","DOMINIC","PAINE","JESPER","FOSS","KOKUBO","TSUNEHISA","CAMERON","SUMPTER","SORE","AOYAMA","THONGDEE","SUYONG","HUNJAE","TOSHIHIDE","BOYD","BAN","QUAH","KWOK","MACLEISH","DUNCAN","NAKAE","JUDY","KAWASHIMA","BIGGS","KAY","MANDEL","GIELTY","CELIA","SPANIDIS","BEER","IRFAAN","LALANI","NATHAN","QUELOS","PASCALE","EMMS","KANA","JIHYUN","KOMURA","BUERKI","PIN","HEDEYUKI","VANDERLIN","THUNGA","DUYKHANH","LEMUEL","CHINGWEN","MARCELIN","QUOCTU","VANTHUY","REHBERGER","SAORI","OZAKI","DEREK","SYLVAN","KUNIAKI","BUMSIK","JEROME","DUBIN","THEANH","RIAN","MCKEA","WOOJOON","DR","BRITTA","MISCH","ADACHI","JIYEON","CHIORI","NIWA","EDNA","AFAMEFUNA","OBI","ONYEBUCHI","VIETANH","KUEHN","DUM","JARUNEE","THICH","MARINO","KISHI","URUSOVA","THANHLUAN","DELL","ACQUA","IHSA","BACHLONG","QIANWEI","GUYEN","HUEBNER","JONGHO","TOMKINS","KOKETSU","MYUNGHEE","KAWANE","HOSHINO","OLESYA","KENSUKE","AZUMADA","HYUNKYU","BERGAMIN","CHRISTEL","TANTAI","SHAMASH","ALPHONSE","ALBIN","ALLEN","LEMOINE","TERSKAYA","PAWELA","UCHENNA","AMARACHI","OSONDU","THIMAITHY","KAGIN","MORIYAMA","TOMOYUKI","LINTHORST","LIUDMILA","SOONMO","ANHTUAN","TRUSA","DOROTHY","OMANOFF","VAGHELA","ELFI","STRACKX","QUOCTHAI","HOLMES","FUKUTA","FERRARO","VIJAY","UPPAL","LIRAZ","EVENOR","TANTHINH","CANGIA","UOC","HARDY","YISA","VIVIEN","WM","JAMIESON","BORIS","BRINKMAN","THISOAN","JURAJ","UVIRA","DUBOUIS","KEISUKE","DAIMON","FUNAKI","NOIJ","PRUDEN","SIEU","HORNE","GABYSHEVA","NAKAYA","HUW","DAVIES","BRIONY","CHHAN","LINAS","PANKUNAS","JIMMY","MINHTU","SHEEHAN","EDDIE","ARGAUD","SHELABNEV","SORAYA","LESTA","YAMANE","CHENMING"};
void putTextCairo(
        cv::Mat &targetImage,
        std::string const& text,
        cv::Point2d centerPoint,
        std::string const& fontFaceStr,
        double fontSize,
        cv::Scalar textColor,
        bool fontItalic,
        bool fontBold)
{
    // Create Cairo
    cairo_surface_t* surface =
            cairo_image_surface_create(
                CAIRO_FORMAT_ARGB32,
                targetImage.cols,
                targetImage.rows);

    cairo_t* cairo = cairo_create(surface);

    // Wrap Cairo with a Mat
    cv::Mat cairoTarget(
                cairo_image_surface_get_height(surface),
                cairo_image_surface_get_width(surface),
                CV_8UC4,
                cairo_image_surface_get_data(surface),
                cairo_image_surface_get_stride(surface));

    // Put image onto Cairo
    cv::cvtColor(targetImage, cairoTarget, cv::COLOR_BGR2BGRA);

    // Set font and write text
    cairo_select_font_face (
                cairo,
                fontFaceStr.c_str(),
                fontItalic ? CAIRO_FONT_SLANT_ITALIC : CAIRO_FONT_SLANT_NORMAL,
                fontBold ? CAIRO_FONT_WEIGHT_BOLD : CAIRO_FONT_WEIGHT_NORMAL);

    cairo_set_font_size(cairo, fontSize);
    cairo_set_source_rgb(cairo, textColor[2], textColor[1], textColor[0]);

    cairo_text_extents_t extents;
    cairo_text_extents(cairo, text.c_str(), &extents);

    cairo_move_to(
                cairo,
                centerPoint.x - extents.width/2 - extents.x_bearing,
                centerPoint.y - extents.height/2- extents.y_bearing);
    cairo_show_text(cairo, text.c_str());

    // Copy the data to the output image
    cvtColor(cairoTarget, targetImage, cv:: COLOR_BGRA2BGR);

    cairo_destroy(cairo);
    cairo_surface_destroy(surface);
}

vector<string> readFile(const string& pattern){
    string STRING;
    ifstream infile;
    vector<string> v;
    infile.open (pattern);
    cout << pattern << "\n";
    while(!infile.eof()) // To get you all the lines.
    {
        getline(infile,STRING); // Saves the line in STRING.
        v.push_back(STRING);
    }
    infile.close();

    return v;
}



void createMask( Mat & img, Mat & mask, Size textSize, string fontFaceStr, string text){

    // write text to white background
    putTextCairo(img,text, cv::Point2d(textSize.width/2 , textSize.height/2), fontFaceStr, 29, Scalar(0,0,0), false, false);
    

    cvtColor(img, mask, CV_BGR2GRAY);
    threshold(mask, mask, 240, 255, THRESH_BINARY);
    bitwise_not (mask, mask);

    const int range_from  = -5;
    const int range_to    = 5;
    std::random_device                  rand_dev;
    std::mt19937                        generator(rand_dev());
    std::uniform_int_distribution<int>  distr(range_from, range_to);

    std::uniform_int_distribution<int>  distr1(-10000, 10000);

    Mat fullImageHSV;
    cvtColor(img, fullImageHSV, CV_BGR2HSV);
    for(int y=0;y<fullImageHSV.rows;y++){
        for(int x=0;x< fullImageHSV.cols;x++){
            Vec3b & intensity = fullImageHSV.at<Vec3b>(y,x);
            // cout<< "image : "<< y << "-" << x << "\n";
                
            if((float)(intensity.val[2]) < 0.55 * 255  ){
                //cout<< (float)(intensity.val[0])<< ","<< (float)(intensity.val[1])<< ","<< (float)(intensity.val[2]) <<"\n";
            
                // randomly for black (0,0,0)

                
                if (distr1(generator) % 20 == 0){
                    Vec3b & intensity2 = fullImageHSV.at<Vec3b>(y,x);
                    intensity2.val[0] = 90 + distr(generator);
                    intensity2.val[1] = 13/100.0 * 255+ distr(generator);
                    intensity2.val[2] = 88/100.0 * 255+ distr(generator);

                    //cout<< "--" << (float)(intensity2.val[0])<< ","<< (float)(intensity2.val[1])<< ","<< (float)(intensity2.val[2]) <<"\n";
            
                    fullImageHSV.at<Vec3b>(y,x) = intensity2;

                } 
                else if (distr1(generator) % 20 < 5){
                    Vec3b & intensity2 = fullImageHSV.at<Vec3b>(y,x);
                    intensity2.val[0] = 176/2 + distr(generator);
                    intensity2.val[1] = 19/100.0 * 255+ distr(generator);
                    intensity2.val[2] = 57/100.0 * 255+ distr(generator);

                    //cout<< "--" << (float)(intensity2.val[0])<< ","<< (float)(intensity2.val[1])<< ","<< (float)(intensity2.val[2]) <<"\n";
            
                    fullImageHSV.at<Vec3b>(y,x) = intensity2;
                } 
                else if (distr1(generator) % 20  < 15){
                    Vec3b & intensity2 = fullImageHSV.at<Vec3b>(y,x);
                    intensity2.val[0] = 162/2 + distr(generator);
                    intensity2.val[1] = 10/100.0 * 255+ distr(generator);
                    intensity2.val[2] = 78/100.0 * 255+ distr(generator);

                    //cout<< "--" << (float)(intensity2.val[0])<< ","<< (float)(intensity2.val[1])<< ","<< (float)(intensity2.val[2]) <<"\n";
            
                    fullImageHSV.at<Vec3b>(y,x) = intensity2;
                } else {
                    Vec3b & intensity2 = fullImageHSV.at<Vec3b>(y,x);
                    intensity2.val[0] = 160/2 + distr(generator);
                    intensity2.val[1] = 19/100.0 * 255+ distr(generator);
                    intensity2.val[2] = 94/100.0 * 255+ distr(generator);

                    //cout<< "--" << (float)(intensity2.val[0])<< ","<< (float)(intensity2.val[1])<< ","<< (float)(intensity2.val[2]) <<"\n";
            
                    fullImageHSV.at<Vec3b>(y,x) = intensity2;

                }

            } else {  // randomly for other

                if (distr1(generator) % 15  < 10){
                    Vec3b & intensity2 = fullImageHSV.at<Vec3b>(y,x);
                    intensity2.val[0] = 162/2 + distr(generator);
                    intensity2.val[1] = 10/100.0 * 255+ distr(generator);
                    intensity2.val[2] = 78/100.0 * 255+ distr(generator);

                    //cout<< "--" << (float)(intensity2.val[0])<< ","<< (float)(intensity2.val[1])<< ","<< (float)(intensity2.val[2]) <<"\n";
            
                    fullImageHSV.at<Vec3b>(y,x) = intensity2;
                } else {
                    Vec3b & intensity2 = fullImageHSV.at<Vec3b>(y,x);
                    intensity2.val[0] = 162/2 + distr(generator);
                    intensity2.val[1] = 19/100.0 * 255+ distr(generator);
                    intensity2.val[2] = 94/100.0 * 255+ distr(generator);

                    //cout<< "--" << (float)(intensity2.val[0])<< ","<< (float)(intensity2.val[1])<< ","<< (float)(intensity2.val[2]) <<"\n";
            
                    fullImageHSV.at<Vec3b>(y,x) = intensity2;

                }

            }
            
        }
    }

    cvtColor(fullImageHSV,img, CV_HSV2BGR);
}

const vector<string> backgrounds = readFile(BASE + "/utils/backgrounds.txt");
const int background_size = backgrounds.size();

Mat getBackground(Size textSize){

    // readFile("/Volumes/Data/WORKSPACE/git/bagiks/CMT-Text-Detection/dataset/bg/");
    
    cout << "*************" << 210 << "\n";

    string background;
    Mat bg_mat;

    std::random_device                  rand_dev;
    std::mt19937                        generator(rand_dev());
    std::uniform_int_distribution<int>  distr(0, background_size - 1);

    cout << "*************" << 218 << "\n";
    do {
        bg_mat.release();
        background = backgrounds.at(distr(generator));
        cout << "*************" << 222 << "\n";
        bg_mat = imread(background);
    } while (bg_mat.cols <= textSize.width + 10 ||  bg_mat.rows <= textSize.height + 5);

    // cout << background << "\n";
    // cout << bg_mat.cols - textSize.width  << "\n";
    // cout << bg_mat.rows - textSize.height  << "\n";
    
    cout << "*************" << 228 << "\n";
    
    Rect roi;
    
    roi.width = textSize.width ;
    roi.height = 31;//textSize.height ;


    std::uniform_int_distribution<int>  distrX(1, bg_mat.cols - textSize.width -9);
    std::uniform_int_distribution<int>  distrY(1, bg_mat.rows -  textSize.height -5);
    roi.x = distrX(generator);
    roi.y = distrY(generator);

    cout << "*************" << 242 << "\n";

    // cout << textSize.width <<"-+-"<<  textSize.height << "\n";
    // cout << bg_mat.cols <<"-+-"<<  bg_mat.rows << "\n";
    // cout << bg_mat(roi).cols <<"-+-"<<  bg_mat(roi).rows << "\n";



    return bg_mat(roi);

}

Size getTextSizeFromText(string text){
    int fontFace = FONT_HERSHEY_SCRIPT_SIMPLEX;
    double fontScale = 1.0;
    int thickness = 1;
    int baseline= 1 ;
    
    Size textSize = getTextSize(text, fontFace,
                            fontScale, thickness, &baseline);


    std::random_device                  rand_dev;
    std::mt19937                        generator(rand_dev());
    std::uniform_int_distribution<int>  distr(4,6);

    cout << "*************" << 266 << "\n";
    textSize.width -= distr(generator);


    textSize.height += distr(generator) ;
    baseline += thickness;
    return textSize;
}



int main( int argc, const char** argv )
{
    
    ofstream trainFile;
    trainFile.open(BASE + "dataset/trainFile.txt", std::ios_base::app);
    
    std::vector<string> texts = readFile(BASE + "dataset/training.csv");
    
    string text = "";
    Mat mask, background, crop, dst;
    Size textSize;
    string fontFaceStr = "Times";//"maszyna";//"Times"; //"Traveling _Typewriter";
    double alpha = 0.95;

    // using Iter = std::vector<int>::const_iterator;
    int i = 0;
    for (std::vector<string>::iterator it = texts.begin() ; it!=texts.end(); ++it) {
        
        cout << "???" << i << "-"<< *it<< "\n";
        text = *it;
        i++;
        textSize = getTextSizeFromText(text);

        // creat text image  and its mask
        Mat img( 31 , textSize.width , CV_8UC3, Scalar(255,255,255));
        
        createMask(img, mask, textSize, fontFaceStr, text);

        // make background
        background = getBackground(textSize);

        
        // write text to background
        crop = background.clone();
        putTextCairo(crop,text, cv::Point2d(textSize.width/2 , textSize.height/2), fontFaceStr, 29, Scalar(124/255.0, 125/255.0, 85/255.0), false, false);

        resize(crop, crop, Size(), 10,10, INTER_CUBIC);
        resize(crop, crop, Size(), 0.1,0.1, INTER_AREA);
        
        addWeighted(crop, alpha, background, 1.0-alpha, 0.0, dst);

        // put things together
        img.copyTo(dst,mask);

        namedWindow("MyWindow", CV_WINDOW_AUTOSIZE); //create a window with the name "MyWindow"
        imwrite(BASE+ "dataset/words/"+ to_string(i) + ".jpg", dst);

        trainFile << BASE+ "dataset/words/" << i << ".jpg " << text << "\n";


        crop.release(); 
        mask.release();
        background.release();

    }

    trainFile.close();


    
    // imshow("MyWindow", dst); //display the image which is stored in the 'img' in the "MyWindow" window

    // waitKey(0); //wait infinite time for a keypress

    // destroyWindow("MyWindow"); //destroy the window with the name, "MyWindow"

    return 0;
}




